services:
    sing-box-fscarmen:
        image: ghcr.io/minlaxz/nekohasekai:fscarmen-sb
        container_name: sing-box-fscarmen
        restart: unless-stopped
        ports:
            - "8800-8820:8800-8820/tcp"
            - "8800-8820:8800-8820/udp"
        environment:
            - START_PORT=8800
            - SERVER_IP=
            - XTLS_REALITY=true
            - HYSTERIA2=true
            - TUIC=true
            - SHADOWTLS=true
            - SHADOWSOCKS=true
            - TROJAN=true
            - VLESS_WS=true
            - H2_REALITY=true
            - GRPC_REALITY=true
            - UUID=
            - CDN=www.csgo.com
            - NODE_NAME=sing-box
            - ARGO_DOMAIN=
            - ARGO_AUTH=