services:
    sing-box-fscarmen:
        image: ghcr.io/minlaxz/nekohasekai:fscarmen-sb
        container_name: sing-box-fscarmen
        restart: unless-stopped
        ports:
            - "8800-8820:8800-8820/tcp"
            - "8800-8820:8800-8820/udp"
        env_file:
            - .env
