networks:
  default:
    external: true
    name: proxy-net

services:
  sing-box:
    image: ghcr.io/sagernet/sing-box
    container_name: sing-box
    restart: unless-stopped
    expose:
      - your-server-port
    ports:
      - "your-server-port:your-container-port"
    environment:
      VIRTUAL_HOST: your-server-name
      VIRTUAL_PORT: your-server-port
      LETSENCRYPT_HOST: your-server-name
    volumes:
      - .:/etc/sing-box/
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
