networks:
  default:
    name: proxy-net
    external: true

services:
  sing-box:
    image: ghcr.io/sagernet/sing-box
    restart: unless-stopped
    expose:
      - "29443/udp"
    volumes:
      - ./config.json:/etc/sing-box/config.json
      - ./hy2.log:/etc/sing-box/hy2.log
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
