name: Build sing-box rules from OONI data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: ooni/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ooni/requirements.txt

      - name: Run script
        run: |
          python ooni/probe.py
          python ooni/resolver.py
          sed -i 's/^/*. /' ooni/domains.lst
          mv ooni/domains.lst ooni/include-domain-minpersonal.lst
          mv ooni/ips.lst ooni/include-ip-minpersonal.lst

      - name: Download converter tool
        run: |
          curl -Lo generate-geoip-geosite.tar.gz https://github.com/Dunamis4tw/generate-geoip-geosite/releases/download/v1.3.1/generate-geoip-geosite-1.3.1-linux-amd64.tar.gz
          tar -xzf generate-geoip-geosite.tar.gz
          chmod +x generate-geoip-geosite
          

      # - name: Convert files to LF (Unix format)
      #   run: |
      #     sudo apt-get update && sudo apt-get install -y dos2unix
      #     find . -type f -name "*.lst" -exec dos2unix {} \;

      - name: Convert to sing-box rules
        run: |
          ./generate-geoip-geosite -i ./ooni -o ./ooni/route-rules
          ls -R .

      - name: Deploy to GitHub Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_branch: route-rules
          publish_dir: ooni/route-rules
          force_orphan: true
