name: "Build and push fscarmen-sb image"

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Build:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
        id-token: write

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          context: ./fscarmen-sb
          target: dist
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:fscarmen-sb